config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls")),
    path('accounts/',include("allauth.urls")),# ←allauthのurls.pyを登録
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    #検索ページ
    path('search/', views.search, name="search"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('delete/<uuid:video_pk>/', views.delete, name="delete"),
    path('update/<uuid:video_pk>/', views.update, name="update"),


    path('single/<uuid:video_pk>/', views.single, name="single"),
    path('single_mod/<uuid:video_pk>/', views.single_mod, name="single_mod"),

    ##ランキングページ。DBからデータ抜き取って表示するだけ。GET文だけ
    path('rank/', views.rank, name="rank"),

    # 以下認証済みユーザー専用
    path('mypage/', views.mypage, name="mypage"),
    path('history/', views.history, name="history"),
    path('recommend/', views.recommend, name="recommend"),
    path('notify/', views.notify, name="notify"),
    path('mylist/', views.mylist, name="mylist"),
    path('upload', views.upload, name="upload"),
    path('config/', views.config, name="config"),

]

tube/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.validators import MinValueValidator

import uuid


class Category(models.Model):

    class Meta:
        db_table = "category"

    # TIPS:数値型の主キーではPostgreSQLなど一部のDBでエラーを起こす。それだけでなく予測がされやすく衝突しやすいので、UUID型の主キーに仕立てる。
    id     = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    name   = models.CharField(verbose_name="カテゴリ名", max_length=20)

    def __str__(self):
        return self.name


class Video(models.Model):

    class Meta:

        db_table = "video"

    id       = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    category = models.ForeignKey(Category, verbose_name="カテゴリ", on_delete=models.PROTECT)
    dt       = models.DateTimeField(verbose_name="投稿日", default=timezone.now)

    title        = models.CharField(verbose_name="タイトル", max_length=50)
    description  = models.CharField(verbose_name="動画説明文", max_length=300)
    movie        = models.FileField(verbose_name="動画", upload_to="tube/movie", blank=True)
    thumbnail    = models.ImageField(verbose_name="サムネイル", upload_to="tube/thumbnail/", null=True)
    user         = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    edited       = models.BooleanField(default=False)

    mime         = models.TextField(verbose_name="MIMEタイプ", null=True)

    views        = models.IntegerField(verbose_name="再生回数", default=0, validators=[MinValueValidator(0)])

    def __str__(self):
        return self.title


class VideoComment(models.Model):

    class Meta:
        db_table = "comment"

    id      = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    content = models.CharField(verbose_name="コメント文", max_length=500)
    target  = models.ForeignKey(Video, verbose_name="コメント先の動画", on_delete=models.CASCADE)
    dt      = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="投稿者", on_delete=models.CASCADE)

    def __str__(self):
        return self.content

class History(models.Model):

    class Meta:
        db_table     = "history"

    id     = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    dt     = models.DateTimeField(verbose_name="視聴日時", default=timezone.now)
    target = models.ForeignKey(Video, verbose_name="視聴した動画", on_delete=models.CASCADE)
    user   = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="視聴したユーザー", on_delete=models.CASCADE)
    views  = models.IntegerField(verbose_name="視聴回数", default=1, validators=[MinValueValidator(1)])

    def __str__(self):
        return self.target.title


class MyList(models.Model):

    class Meta:
        db_table    = "mylist"

    id       = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    dt       = models.DateTimeField(verbose_name="登録日時", default=timezone.now)
    target   = models.ForeignKey(Video, verbose_name="マイリスト動画", on_delete=models.CASCADE)
    user     = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="登録したユーザー", on_delete=models.CASCADE)

    def __str__(self):
        return self.target.title


class Notify(models.Model):

    class Meta:
        db_table     = "notify"

    id      = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    dt      = models.DateTimeField(verbose_name="通知日時", default=timezone.now)
    content = models.CharField(verbose_name="通知内容", max_length=200)

    def __str__(self):
        return self.content


class GoodVideo(models.Model):

    class Meta:
        db_table    = "good_video"

    id      = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    dt      = models.DateTimeField(verbose_name="評価日時", default=timezone.now)
    target  = models.ForeignKey(Video, verbose_name="対象動画", on_delete=models.CASCADE)
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="高評価したユーザー", on_delete=models.CASCADE)

    def __str__(self):
        return self.target.title


class BadVideo(models.Model):

    class Meta:
        db_table = "bad_video"

    id      = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    dt      = models.DateTimeField(verbose_name="評価日時", default=timezone.now)
    target  = models.ForeignKey(Video, verbose_name="対象動画", on_delete=models.CASCADE)
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="低評価したユーザー", on_delete=models.CASCADE)

    def __str__(self):
        return self.target.title



tube/forms.py
from django import forms
from .models import Video
from users.models import CustomUser


class VideoEditForm(forms.ModelForm):
    class Meta:
        model  = Video
        fields = ["title", "description", "dt",]

class IconForm(forms.ModelForm):
    class Meta:
        model  = CustomUser
        fields = ["usericon",]

tube/views.py
from rest_framework import status,views,response

from django.shortcuts import render, redirect

from django.db.models import Q

from django.http.response import JsonResponse

from django.template.loader import render_to_string

from django.core.paginator import Paginator

from django.conf import settings

#TIPS:ログイン状態かチェックする。ビュークラスに継承元として指定する(多重継承なので順番に注意)。未ログインであればログインページへリダイレクト。
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from .models import Video,Category,VideoComment,MyList,History,GoodVideo,BadVideo
from users.models import CustomUser

from .forms import VideoEditForm,IconForm
from .serializer import VideoSerializer,VideoEditSerializer,VideoCommentSerializer,MyListSerializer,HistorySerializer,RateSerializer,GoodSerializer,BadSerializer

DEFAULT_VIDEO_AMOUNT = 10
COMMENTS_AMOUNT_PAGE = 10

#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

import magic
ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 200 * 1000 * 1000

SEARCH_AMOUNT_PAGE  = 20

#トップページ
class IndexView(views.APIView):

    def get(self, request, *args, **kwargs):

        latests = Video.objects.all().order_by("-dt")[:DEFAULT_VIDEO_AMOUNT]

        if request.user.is_authenticated:
            histories   = History.objects.filter(user=request.user.id).order_by("?")[:DEFAULT_VIDEO_AMOUNT]
        else:
            histories   = False
        '''
        paginator  = Paginator(latests,7)
        

        if "page" in request.GET:
            latests    = paginator.get_page(request.GET["page"])
        else:
            latests    = paginator.get_page(1)
        '''
        context = {"latests": latests,
                   "histories":histories,}

        return render(request, "tube/index.html", context)

index = IndexView.as_view()

#アップロードページ
class UploadView(LoginRequiredMixin,views.APIView):

    def get(self,request, *args, **kwargs):

        categories = Category.objects.all()
        context = {"categories": categories}

        return render(request, "tube/upload.html", context)


    def post(self, request, *args, **kwargs):

        print(request.data)

        request.data["user"]    = request.user.id
        serializer              = VideoSerializer(data=request.data)
        mime_type               = magic.from_buffer(request.FILES["movie"].read(1024), mime=True)

        print(request.data["movie"].size)
        print(type(request.data["movie"].size))

        if request.FILES["movie"].size >= LIMIT_SIZE:
            mb = str(LIMIT_SIZE / 1000000)

            json = {"error": True,
                    "message": "The maximum file size is " + mb + "MB"}

            return JsonResponse(json)

        if mime_type not in ALLOWED_MIME:
            mime = str(ALLOWED_MIME)
            json = {"error": True,
                    "message": "The file you can post is " + mime + "."}

            return JsonResponse(json)

        if serializer.is_valid():
            serializer.save()
        else:
            json    = { "error":True,
                        "message":"入力内容に誤りがあります。" }
            return JsonResponse(json)

        json    = { "error":False,
                    "message":"アップロード完了しました。" }

        return JsonResponse(json)


upload = UploadView.as_view()



#検索結果表示ページ
class SearchView(views.APIView):

    def get(self, request, *args, **kwargs):

        query = Q()
        page = 1

        if "word" in request.GET:

            word_list = request.GET["word"].replace("　", " ").split(" ")
            for w in word_list:
                query &= Q(Q(title__icontains=w) | Q(description__icontains=w))

        if "page" in request.GET:
            page = request.GET["page"]

        videos = Video.objects.filter(query).order_by("-dt")
        amount = len(videos)

        videos_paginator = Paginator(videos, SEARCH_AMOUNT_PAGE)
        videos           = videos_paginator.get_page(page)

        context = {"videos": videos,
                   "amount": amount}

        return render(request, "tube/search.html", context)

search = SearchView.as_view()


#動画個別ページ
class SingleView(views.APIView):

    def get(self,request, video_pk, *args, **kwargs):

        video = Video.objects.filter(id=video_pk).first()

        #Todo:F5で再生回数水増し可能。
        video.views = video.views + 1
        video.save()

        if request.user.is_authenticated:
            print("認証済みユーザーです")

            history = History.objects.filter(user=request.user.id, target=video_pk).first()

            if history:
                print("存在する場合の処理")
                history.views   = history.views + 1
                history.dt      = timezone.now()
                history.save()
            else:
                print("履歴に存在しない場合の処理")
                data        = { "target":video_pk,
                                "user":request.user.id,}
                serializer  = HistorySerializer(data=data)

                if serializer.is_valid():
                    serializer.save()

        comments    = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        good        = GoodVideo.objects.filter(target=video_pk)
        bad         = BadVideo.objects.filter(target=video_pk)

        already_good    = GoodVideo.objects.filter(target=video_pk, user=request.user.id)
        already_bad     = BadVideo.objects.filter(target=video_pk, user=request.user.id)
        relates         = Video.objects.filter(category=video.category).order_by("-dt")


        paginator = Paginator(comments, 10)
        '''
        if "page" in request.GET:
            comments = paginator.get_page(request.GET["page"])
        else:
        '''
        comments = paginator.get_page(1)

        context = {"video": video,
                   "comments": comments,
                   "good": good,
                   "bad": bad,
                   "already_good": already_good,
                   "already_bad": already_bad,
                   "relates": relates,
                   }

        return render(request, "tube/single.html", context)

    def post(self,request,video_pk,*args,**kwargs):

        return JsonResponse(json)

        # return redirect("tube:videos",video_pk=video_pk)

single = SingleView.as_view()


class SingleModView(LoginRequiredMixin,views.APIView):

    #ここでコメントのページネーション↑ のクラス名変えるべきでは？
    def get(self,request,video_pk,*args,**kwargs):

        page        = 1
        if "page" in request.GET:
            page    = request.GET["page"]

        video               = Video.objects.filter(id=video_pk).first()
        comments            = VideoComment.objects.filter(target=video_pk).order_by("-dt")
        comments_paginator  = Paginator(comments,COMMENTS_AMOUNT_PAGE)
        comments            = comments_paginator.get_page(page)

        #コメントをrender_to_stringテンプレートを文字列化、json化させ返却
        context     = { "comments":comments,
                        "video":video,
                        }
        content     = render_to_string('tube/comments.html', context ,request)

        json        = { "error":False,
                        "content":content,
                        }

        return JsonResponse(json)


    def post(self, request, video_pk, *args, **kwargs):


        copied   = request.POST.copy()

        copied["target"]  = video_pk
        copied["user"]    = request.user.id

        serializer  = VideoCommentSerializer(data=copied)
        json        = {}

        if serializer.is_valid():
            print("コメントバリデーションOK")
            serializer.save()

            comments    = VideoComment.objects.filter(target=video_pk).order_by("-dt")
            comments_paginator  = Paginator(comments,COMMENTS_AMOUNT_PAGE)
            comments            = comments_paginator.get_page(1)
            video               = Video.objects.filter(id=video_pk).first()

            context     = { "comments":comments,
                            "video":video,
                            }



            content     = render_to_string('tube/comments.html', context, request)

            json        = { "error":False,
                            "message":"投稿完了",
                            "content":content,
                            }

        else:
            print("コメントバリデーションNG")
            json        = {"error":True,
                           "message":"入力内容に誤りがあります。",
                           "content":"",
                           }


        return JsonResponse(json)

    def patch(self,request,video_pk,*args,**kwargs):

        serializer  = RateSerializer(data=request.data)

        if serializer.is_valid():

            validated_data  = serializer.validated_data

            if validated_data["flag"]:

                data    = GoodVideo.objects.filter(user=request.user.id, target=video_pk).first()

                if data:
                    data.delete()
                    print("削除")
                else:
                    data    = { "user":request.user.id,
                                "target":video_pk,
                                }
                    serializer  = GoodSerializer(data=data)

                    if serializer.is_valid():
                        print("セーブ")
                        serializer.save()
                    else:
                        print("バリデーションエラー")

            else:

                data    = BadVideo.objects.filter(user=request.user.id, target=video_pk).first()

                if data:
                    data.delete()
                    print("削除")
                else:

templates/tube/config.html
{% extends "tube/mypage_base.html" %}
{% load static %}


{% block mypage_content %}

<h2>設定</h2>

<!--ユーザーモデルに設定欄を追加させる-->







{% endblock %}

templates/tube/delete.html
{% extends "tube/base.html" %}
{% load static %}
{% load param_change %}

{% block main %}

{% block extra_head %}
{{ block.super }}

 <style>
    h2 {
       color: #F36C21;
       font-weight: bold;
       }
 </style>
{% endblock %}



{% block page_title %}{% endblock %}


    <h2>動画削除ページ</h2>
    <div>
        <p>一度削除すると、元に戻すことが出来ません。本当に削除しますか？</p>
    </div>

          <form action="{% url 'tube:delete' video.id %}" method ="POST" style="display:inline-block;">
            {% csrf_token %}
            <button class="btn-gradient-delete">Yes</button>
          </form>

          <a class="btn-gradient-success" href="{% url 'tube:mypage' %}">No</a>



{% endblock %}

templates/tube/history.html
{% extends "tube/mypage_base.html" %}
{% load static %}
{% load param_change %}


{% block mypage_content %}

<h2>視聴履歴</h2>

<!--TODO:ここに複数選択削除のフォームを-->


    {% if amount > 0 %}
    <div>{{ amount }}件中、{{ histories|length }}件表示しています。</div>
    {% endif %}

{% for history in histories %}
<div class="video_list_view">

    <div class="video_list_thumbnail_area">
        {% if history.target.thumbnail %}
        <a class="video_list_thumbnail" href="{% url 'tube:single' history.target.id %}"><img src="/media/{{ history.target.thumbnail }}" alt="thumbnail"></a>
        {% else %}
        <a class="video_list_thumbnail" href="{% url 'tube:single' history.target.id %}"><img src="{% static 'tube/img/no-img.png' %}" alt="thumbnail"></a>
        {% endif %}
    
    </div>
    <div class="video_list_description_area">
        <div class="video_list_description_inner">
            <h3 class="video_list_title"><a class="video_list_title_link" href="{% url 'tube:single' history.target.id %}">{{ history.target.title }}</a></h3>
            <div>{{ history.target.user.handle_name }}</div>
            <div class="video_list_description_overflow">{{ history.target.description }}</div>
            <div>視聴日時:{{ history.dt|date:"Y年m月d日 H時i分s秒" }} - {{ history.views }} 回視聴</div>
        </div>
    </div>

</div>
{% empty %}
<p>視聴履歴はありません。</p>
{% endfor %}

     {% generate_pagelink request "page" "1" histories.paginator.num_pages histories.number %}

{% endblock %}

templates/tube/index.html
{% extends "tube/base.html" %}
{% load static %}
{% load param_change %}

{% block main %}

{% block extra_head %}
{{ block.super }}
{% endblock %}



{% block page_title %}{% endblock %}


{% include "tube/search_form.html" %}


    {% if recommends %}
    <h2 class="violet">おすすめ</h2>

    <div class="video_content_list">

        <div class="video_content">
            <a class="video_content_link" href="">
                <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="動画タイトル">
                <div class="video_title">タイトル</div>
            </a>
        </div>

    </div>
    {% endif %}


    {% if histories %}
    <h2 class="violet">もう一度見る</h2>

    <div class="video_content_list">

        {% for history in histories %}
        <div class="video_content">
            <a class="video_content_link" href="{% url 'tube:single' history.target.id %}">
                {% if history.target.thumbnail %}
                <img class="video_thumbnail" src="/media/{{ history.target.thumbnail }}" alt="{{ history.target.title }}">
                {% else %}
                <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ history.target.title }}">
                {% endif %}
                <div class="video_title">{{ history.target.title }}</div>
            </a>
        </div>
        {% endfor %}

    </div>
    {% endif %}


    {% if ranks %}
    <h2>総合ランキング</h2>

    <div class="video_content_list">
        <div class="video_content">
            <a class="video_content_link" href="">
                <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="動画タイトル">
                <div class="video_title">タイトル</div>
            </a>
        </div>
    </div>
    {% endif %}


    <h2 class="violet">新着動画</h2>

    <div class="video_content_list">

        {% for latest in latests %}
        <div class="video_content">
            <a class="video_content_link" href="{% url 'tube:single' latest.id %}">
                {% if latest.thumbnail %}
                <img class="video_thumbnail" src="/media/{{ latest.thumbnail }}" alt="{{ latest.title }}">
                {% else %}
                <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ latest.title }}">
                {% endif %}
                <div class="video_title">{{ latest.title }}</div>
            </a>
        </div>
        {% empty %}
        <div class="video_content">動画がありません</div>
        {% endfor %}

    </div>


{% endblock %}





templates/tube/mypage.html
{% extends "tube/mypage_base.html" %}
{% load static %}


{% block mypage_content %}



    <h2>基本情報</h2>

    <table>
        <tr>
            <td>ユーザー名</td>
            <td>{{ request.user }}</td>
        </tr>
        <tr>
            <td>最終ログイン</td>
            <td>{{ request.user.last_login }}</td>
        </tr>
        <tr>
            <td>メールアドレス</td>
            <td>{{ request.user.email }}</td>
        </tr>
    </table>

    <form method="POST" action="{% url 'tube:mypage' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div>アイコン指定(jpeg,png)：<input type="file" accept=".jpg,.png" name="usericon"></div>
        <input class="btn-gradient-radius" type="submit" value="送信">
    </form>

    <h2>投稿した動画</h2>


    <div class="video_content_list">
        {% for video in videos %}
        <div class="video_content">
            <a class="video_content_link" href="{% url 'tube:single' video.id %}">
                {% if video.thumbnail %}
                <img class="video_thumbnail" src="/media/{{ video.thumbnail }}" alt="{{ video.title }}">
                {% else %}
                <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ video.title }}">
                {% endif %}

                <div class="video_title">{{ video.title }}</div>
            </a>
        </div>
        {% empty %}
        <div class="video_content"><p>投稿した動画はありません。<a href="{% url 'tube:upload' %}">アップロード</a>から投稿できます。</p></div>
        {% endfor %}
    </div>
    
    <h2>高く評価した動画</h2>

    <div class="video_content_list">
        {% for video in good_videos %}
        <div class="video_content">
            <a class="video_content_link" href="{% url 'tube:single' video.target.id %}">
                {% if video.target.thumbnail %}
                <img class="video_thumbnail" src="/media/{{ video.target.thumbnail }}" alt="{{ video.target.title }}">
                {% else %}
                <img class="video_thumbnail" src="{% static 'tube/img/no-img.png' %}" alt="{{ video.target.title }}">
                {% endif %}

                <div class="video_title">{{ video.target.title }}</div>
            </a>
        </div>
        {% empty %}
        <div class="video_content"><p>高評価した動画はありません。</div>
        {% endfor %}
    </div>





{% endblock %}

templates/tube/rank.html
{% extends "tube/base.html" %}
{% load static %}

{% block main %}

{% include "tube/search_form.html" %}

    ランキングページ

    {% for video in videos %}
    <div class="single_video_area">
        <p>{{ video.title }}</p>
        <p>{{ video.description }}</p>
        <a href="{% url 'tube:single' video.id %}">見る</a>
    </div>
    {% endfor %}

{% endblock %}

templates/tube/single.html
{% extends "tube/base.html" %}
{% load humanize %}
{% load static %}
{% load param_change %}

{% block site_title %}TubeIntegrity{% endblock %}


{% block extra_head %}
{{ block.super }}

<!--video.jsのCDNを読み込む-->
<link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>


<!--video.jsのカスタムスキンを指定-->
<link rel="stylesheet" href="{% static 'tube/css/videojs.css' %}">

<script src="{% static 'tube/js/single.js' %}"></script>

{% endblock %}



{% block page_title %}TubeIntegrity{% endblock %}

{% block main %}

         {% include "tube/search_form.html" %}

<div class="single_video_area">
    <div class="single_video_content">
        <div class="single_video_content_inner">
            <!--
            <video class="single_video" src="/media/{{ video.movie }}" controls></video>
            -->
            <video id="video-js" class="single_video video-js vjs-default-skin vjs-big-play-centered vjs-16-9">
                <source src="/media/{{ video.movie }}" type="video/mp4">
            </video>

        </div>
    </div>

    <div class="single_video_subcontent">
        <div class="single_video_subcontent_inner">

            <input id="subcontent_tab_1" class="subcontent_tab_radio" type="radio" name="subcontent_tab" checked><label for="subcontent_tab_1" class="subcontent_tab_label">説明</label>
            <input id="subcontent_tab_2" class="subcontent_tab_radio" type="radio" name="subcontent_tab"><label for="subcontent_tab_2" class="subcontent_tab_label">コメント</label>
            <input id="subcontent_tab_3" class="subcontent_tab_radio" type="radio" name="subcontent_tab"><label for="subcontent_tab_3" class="subcontent_tab_label">関連動画</label>

            {% if request.user == video.user %}
            <input id="subcontent_tab_4" class="subcontent_tab_radio" type="radio" name="subcontent_tab"><label for="subcontent_tab_4" class="subcontent_tab_label">投稿者オプション</label>
            {% endif %}

            <div class="single_video_description">
                {% if video.edited %}
                   <p class="sort"><i class="far fa-edit"></i></p>
                {% endif %}

                <h2>{{ video.title }}</h2>

                {% if video.user.usericon %}
                <img class="usericon" src="/media/{{ video.user.usericon }}" alt="icon">
                {% else %}
                <p class="comment_icon"><i class="fas fa-user"></i></p>
                {% endif %}

                {# 外部キーのuserがカスタムユーザーモデルに繋がっているので、そこからhandle_nameを呼び出せる #}
                <div>{{ video.user.handle_name }}</div>
                <div>{{ video.views|intcomma }} 回 再生 - {{ video.dt|date:"Y年m月d日 H時i分s秒" }}</div>

                <div id="mylist_message" class="js_message"></div>
                <div class="single_video_mod_area">
                    <div id="single_video_rating_area" class="single_video_rating_area">
                        {% include "tube/rate.html" %}
                    </div>
                    <div id="single_video_mylist_area" class="single_video_mylist_area">

                        <form id="mylist_form_area" action="{% url 'tube:mylist' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="target" value="{{ video.id }}">
                            <button id="mylist_submit" class="input_form_button" type="button">マイリストに登録</button>
                        </form>
                    </div>
                </div>

                <div>{{ video.description }}</div>

            </div>

            <div class="single_video_comments">
                 <div id="comments_message" class="js_message"></div>

                 <form id="single_video_comments_form" action="{% url 'tube:single_mod' video.id %}" method="POST" >
                     {% csrf_token %}
                     <textarea class="textarea_form" name="content" placeholder="コメント..." rows="4" maxlength="500"></textarea>
                     <input id="single_video_comments_submit" class="btn-gradient-radius" type="button" value="送信">
                 </form>

                 <div id="video_comments_area">
                     {% include "tube/comments.html" %}
                 </div>


            </div>

            <div class="single_video_relate">

                {% for relate in retales %}
                <div class="video_list_view">

                    <div class="video_list_thumbnail_area">
                        {% if relate.thumbnail %}
                        <a class="video_list_thumbnail" herf="{% url 'tube:single' relate.id %} "><img src="/media/{{ relate.thumbnail }}" alt="thumbnail"></a>
                        {% else %}
                        <a class="video_list_thumbnail" herf="{% url 'tube:single' relate.id %} "><img src="{% static 'tube/img/no-img.png' %}" alt="thumbnail"></a>
                        {% endif %}
                    </div>
                    <div class="video_list_description_area">
                        <div class="video_list_description_inner">
                            <h3 class="video_list_title"><a class="video_list_title_link" href="{% url 'tube:single' relate.id %}">{{ relate.title }}</a></h3>
                            <div>{{ relate.user.handle_name }}</div>
                            <div>{{ relate.description }}</div>
                        </div>
                    </div>

                </div>
                {% empty %}
                <p>関連動画はありません。</p>
                {% endfor %}

            </div>

            {% if request.user == video.user %}
            <div class="single_video_uploader">
                <div>

                {% if video.user.usericon %}
                <img class="usericon" src="/media/{{ video.user.usericon }}" alt="icon">
                {% else %}
                <p class="comment_icon"><i class="fas fa-user"></i></p>
                {% endif %}

                <div>{{ video.user.handle_name }}</div>

                    <a class="btn-gradient-delete" href="{% url 'tube:delete' video.id %}">削除</a>
                    <a class="btn-gradient-success" href="{% url 'tube:update' video.id %}">編集</a>

                    <!-- Ajax でPUTメソッドを送信 -->
                    <form id="video_update_form" action="{% url 'tube:single_mod' video.id %}" method="">
                        {% csrf_token %}
                        <input class="form-control" type="text" value="{{ video.title }}" name="title">
                        <textarea class="form-control" name="description" rows="4">{{ video.description }}</textarea>
                        <button id="video_update" class="btn-gradient-success" type="button">Yes(update method on ajax)</button>
                    </form>
                    

                    <!-- Ajax でDELETEメソッドを送信 -->
                    <form id="video_delete_form" action="{% url 'tube:single_mod' video.id %}" style="...">
                        {% csrf_token %}
                        <button id="video_delete" class="btn-gradient-delete" type="button">Yes(delete method on ajax)</button>
                    </form>

                    <div id="delete_message" class="js_message"></div>

                </div>
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}